"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { AppShell } from "../components/app-shell";
import { SessionCard } from "../components/session-card";
import { getToday, PlanSession } from "../lib/api";
import { cachedPlan } from "../lib/plan-cache";
import { getSavedSession } from "../lib/session";
export default function Today(){const [sessions,setSessions]=useState<PlanSession[]|null>(null);const [planId,setPlanId]=useState("");const [notice,setNotice]=useState("");useEffect(()=>{const saved=getSavedSession();if(!saved){setSessions([]);return;}setPlanId(saved.planId);getToday(saved.planId).then(result=>{if(result.plan_needs_update){setSessions([]);setNotice("Plan needs update — your Profile schedule has changed.");return;}if(result.sessions.length)setSessions(result.sessions);else{const fallback=cachedPlan();const next=fallback?.planId===saved.planId?fallback.plan.sessions.find(session=>session.date>=new Date().toISOString().slice(0,10)):undefined;setSessions(next?[next]:[]);setNotice("No session is scheduled for today; showing your next planned session.");}}).catch(()=>{const fallback=cachedPlan();const next=fallback?.planId===saved.planId?fallback.plan.sessions.find(session=>session.date>=new Date().toISOString().slice(0,10)):undefined;setSessions(next?[next]:[]);setNotice("Couldn’t reach the rowing-plan service — showing your most recently saved plan.");});},[]);return <AppShell title="Today">{notice&&<section className="notice"><p>{notice}</p>{notice.startsWith("Plan needs update")&&<Link href="/profile">Update future plan</Link>}</section>}{sessions===null?<p>Loading your plan…</p>:sessions.length?sessions.map(session=><SessionCard key={`${session.date}-${session.session_id}-${session.mode}`} session={session} planId={planId}/>):<section className="empty"><h2>{notice.startsWith("Plan needs update")?"Plan needs update":"No plan yet"}</h2><p>{notice.startsWith("Plan needs update")?"Regenerate future sessions from your updated Profile schedule.":"Create your athlete profile and plan to see daily guidance."}</p><Link href={notice.startsWith("Plan needs update")?"/profile":"/onboarding"}>{notice.startsWith("Plan needs update")?"Open Profile":"Create my plan"}</Link></section>}</AppShell>}
