"use client";

import { useEffect, useMemo, useState } from "react";
import { AppShell } from "../../components/app-shell";
import { getPlan, getSeason } from "../../lib/api";
import { getSavedSession } from "../../lib/session";
type Phase={date:string;phase:string;race_event?:string};
type Season={current_phase?:Phase;next_race?:{event_name:string;start_date:string;priority:string;distance_m?:number};days_to_next_race?:number;transitions:Phase[]};
const title=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase());
const key=(date:Date)=>date.toISOString().slice(0,10);
export default function Season(){
 const [season,setSeason]=useState<Season|null>(null),[phases,setPhases]=useState<Phase[]>([]),[month,setMonth]=useState<Date|null>(null),[selected,setSelected]=useState<Phase|null>(null);
 useEffect(()=>{const saved=getSavedSession();if(!saved)return;Promise.all([getSeason(saved.planId),getPlan(saved.planId)]).then(([summary,plan])=>{setSeason(summary);setPhases(plan.plan.phases??[]);const first=plan.plan.phases?.[0]?.date;if(first)setMonth(new Date(`${first}T12:00:00`));}).catch(()=>undefined);},[]);
 const cells=useMemo(()=>{if(!month)return [];const start=new Date(month.getFullYear(),month.getMonth(),1),offset=(start.getDay()+6)%7,first=new Date(start);first.setDate(first.getDate()-offset);return Array.from({length:42},(_,index)=>{const day=new Date(first);day.setDate(first.getDate()+index);return day;});},[month]);const phaseByDate=useMemo(()=>new Map(phases.map(item=>[item.date,item])),[phases]);
 return <AppShell title="Season planning">{season?<><section className="race-card"><span className="band">CURRENT PHASE</span><h2>{season.current_phase?title(season.current_phase.phase):"Plan ready"}</h2>{season.next_race?<><p className="duration">{season.days_to_next_race} days to next race</p><p><b>{season.next_race.event_name}</b> · {season.next_race.priority} priority · {season.next_race.distance_m??"custom"} m</p></>:<p>No upcoming race has been added.</p>}</section><section className="session-card"><div className="section-heading"><h2>Month view</h2><div className="month-controls"><button className="quiet" type="button" onClick={()=>setMonth(current=>current?new Date(current.getFullYear(),current.getMonth()-1,1):current)}>Previous</button><button className="quiet" type="button" onClick={()=>setMonth(current=>current?new Date(current.getFullYear(),current.getMonth()+1,1):current)}>Next</button></div></div>{month&&<><p className="month-title">{month.toLocaleString(undefined,{month:"long",year:"numeric"})}</p><div className="month-weekdays">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(day=><span key={day}>{day}</span>)}</div><div className="month-grid">{cells.map(day=>{const phase=phaseByDate.get(key(day)),outside=day.getMonth()!==month.getMonth();return <button type="button" className={`month-day ${outside?"outside":""} ${phase?.phase??""}`} onClick={()=>phase&&setSelected(phase)} key={key(day)} aria-label={`${key(day)}${phase?`, ${title(phase.phase)}`:""}`}><b>{day.getDate()}</b>{phase&&<small>{phase.race_event?"Race":title(phase.phase)}</small>}</button>})}</div></>}</section>{selected&&<section className="session-card selected-phase"><h2>{selected.date}</h2><p><b>{title(selected.phase)}</b>{selected.race_event?` · ${selected.race_event}`:""}</p><button className="quiet" type="button" onClick={()=>setSelected(null)}>Close details</button></section>}<h2>Phase changes</h2>{season.transitions.map(item=><article className="week-row" key={item.date}><b>{item.date}</b><span>{title(item.phase)}</span><span>{item.race_event??""}</span></article>)}</>:<p className="empty">Create a plan to see the season calendar.</p>}</AppShell>;
}
