"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {AppShell} from "../../components/app-shell";
import {generateAthletePlan,getCalendar,getLatestAthletePlan,getPlan,getSeason,Plan} from "../../lib/api";
import {getSavedSession,saveSession} from "../../lib/session";
import {cachePlan} from "../../lib/plan-cache";
const title=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase());
export default function Season(){const [plan,setPlan]=useState<Plan|null>(null),[season,setSeason]=useState<any>(null),[stale,setStale]=useState(false),[status,setStatus]=useState(""),[loading,setLoading]=useState(true);useEffect(()=>{const saved=getSavedSession();if(!saved){setLoading(false);setStatus("Choose an athlete profile before viewing a season.");return;}const load=async()=>{let record:any;try{record=saved.planId?await getPlan(saved.planId):null;if(record?.athlete_id!==saved.athleteId)record=null;}catch{record=null;}if(!record){record=await getLatestAthletePlan(saved.athleteId);saveSession({athleteId:saved.athleteId,planId:record.plan_id});}const summary=await getSeason(record.plan_id);await getCalendar(record.plan_id);setPlan(record.plan);setSeason(summary);setStale(record.plan_needs_update);};load().catch(error=>setStatus(String(error).includes("404")?"No PlanVersion exists yet. Generate a plan from your Profile to view your season.":"Couldn’t load this season. Please try again.")).finally(()=>setLoading(false));},[]);const generate=async()=>{const saved=getSavedSession();if(!saved)return;setLoading(true);try{const next=await generateAthletePlan(saved.athleteId);saveSession({athleteId:saved.athleteId,planId:next.plan_id});cachePlan(next.plan_id,next.plan);setPlan(next.plan);setStatus("Plan generated. Reload Season to view it.");}catch{setStatus("Couldn’t generate a plan. Check your Profile season dates and try again.");}finally{setLoading(false);}};return <AppShell title="Season planning">{loading?<p>Loading season…</p>:status?<section className="empty"><p>{status}</p>{status.startsWith("No PlanVersion")&&<button onClick={generate}>Generate plan</button>}</section>:stale?<section className="notice"><p>Plan needs update.</p><Link href="/profile">Update future plan</Link></section>:plan?<><section className="race-card"><span className="band">CURRENT PHASE</span><h2>{season?.current_phase?title(season.current_phase.phase):"Plan ready"}</h2>{season?.next_race?<p><b>{season.next_race.event_name}</b> · {season.next_race.priority} priority</p>:<p>No upcoming race has been added. Your development season is ready.</p>}</section><section className="session-card"><h2>Season plan</h2><p>{plan.sessions.length} planned sessions across this PlanVersion.</p><h3>Phase changes</h3>{(season?.transitions??[]).map((item:any)=><p key={item.date}><b>{item.date}</b> · {title(item.phase)}{item.race_event?` · ${item.race_event}`:""}</p>)}</section></>:<section className="empty"><p>No PlanVersion exists yet.</p><button onClick={generate}>Generate plan</button></section>}</AppShell>}
