"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { AppShell } from "../../components/app-shell";
import { getSessionDetail } from "../../lib/api";
import { getSavedSession } from "../../lib/session";
import { WorkoutLogSheet } from "../../components/workout-log-sheet";
type Detail={title:string;session_type:string;primary_band:string;planned_duration_min:number;description:string;coach_directed:boolean;erg_targets?:{watts?:number;split?:string;rate?:string;hr?:string}|null;water_targets?:{rate?:string;hr?:string;technical_cue?:string;note?:string}|null;recovery?:string};
export default function Workout(){const [detail,setDetail]=useState<Detail|null>(null);const [error,setError]=useState("");const [session,setSession]=useState<{planId:string;date:string;id:string;mode:string}|null>(null);useEffect(()=>{const params=new URLSearchParams(window.location.search);const saved=getSavedSession();const day=params.get("date"),id=params.get("sessionId"),mode=params.get("mode");if(!saved||!day||!id||!mode){setError("Choose a workout from Today or Week.");return;}setSession({planId:saved.planId,date:day,id,mode});getSessionDetail(saved.planId,day,id,mode).then(data=>setDetail(data as Detail)).catch(()=>setError("Workout details need a connection the first time they are opened."));},[]);if(error)return <AppShell title="Workout"><section className="empty"><p>{error}</p><Link href="/week">Back to Week</Link></section></AppShell>;return <AppShell title="Workout">{detail?<section className="session-card"><span className="band">{detail.session_type.replaceAll("_"," ")}</span><h2>{detail.title}</h2><p className="duration">{detail.planned_duration_min} min · {detail.primary_band}</p>{detail.coach_directed&&<p className="notice">Coach-directed session: your coach’s instructions take priority.</p>}<p className="note">{detail.description}</p>{detail.erg_targets&&<><div className="target"><b>Erg target</b><span>{detail.erg_targets.watts?`${detail.erg_targets.watts} W · ${detail.erg_targets.split??""}`:"Use rate and RPE"}</span></div><div className="target"><b>Rate / HR</b><span>{detail.erg_targets.rate} · {detail.erg_targets.hr}</span></div></>}{detail.water_targets&&<><div className="target"><b>Rate / HR</b><span>{detail.water_targets.rate} · {detail.water_targets.hr}</span></div><div className="target"><b>Technical cue</b><span>{detail.water_targets.technical_cue}</span></div><p className="water-note">{detail.water_targets.note}</p></>}{detail.recovery&&<p><b>Recovery:</b> {detail.recovery}</p>}{session&&<div className="actions"><WorkoutLogSheet planId={session.planId} session={{date:session.date,day:"",band:detail.primary_band,title:detail.title,total_cardio_minutes:detail.planned_duration_min,coached:detail.coach_directed,mode:session.mode,session_id:session.id}} /></div>}</section>:<p>Loading workout…</p>}</AppShell>}
