"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "../../components/app-shell";
import { createAthlete, generateAthletePlan } from "../../lib/api";
import { saveSession } from "../../lib/session";
import { cachePlan } from "../../lib/plan-cache";
const weekdays=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"];
const iso=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
export default function Onboarding(){const router=useRouter();const [name,setName]=useState("");const [days,setDays]=useState<string[]>(["tuesday","wednesday","thursday","sunday"]);const [lifts,setLifts]=useState<string[]>([]);const [rowWithLift,setRowWithLift]=useState(true);const [status,setStatus]=useState("");const toggle=(day:string,setter:(v:string[])=>void,items:string[])=>setter(items.includes(day)?items.filter(x=>x!==day):[...items,day]);async function submit(e:FormEvent){e.preventDefault();setStatus("Creating your plan…");const start=iso(0),end=iso(120),rest="saturday";const profile={profile_version:"0.5",athlete:{display_name:name||"Rower",age_band:"30-39",experience_level:"intermediate",boat_classes:[],medical_review_required:false,coach_review_requested:false},season:{start_date:start,end_date:end,current_weekly_endurance_minutes:180,target_peak_weekly_endurance_minutes:270},goals:[],tests:{resting_hr:58,max_hr:177,erg_2k_seconds:null,multi_duration_power_tests:{},testing_blocks:[]},weekly_availability:weekdays.map(day=>({weekday:day,available:days.includes(day),fixed_rest:day===rest,max_training_minutes:90,max_sessions:1,heavy_lifting:lifts.includes(day),lifting_minutes:lifts.includes(day)?60:0,alternate_ut2_allowed:false,alternate_ut2_modes:[],row_on_lifting_day:rowWithLift,fixed_coached_row:false,expected_coached_intensity:"unknown",rowing_modes:["on_water","erg"],notes:""})),races:[],preferences:{terminology:"UT",erg_primary_display:"both",broken_aerobic_preferred:true,fixed_rest_weekdays:[rest],workbook_detail_level:"detailed",include_sources_sheet:true},locked_weeks:[]};try{const athlete=await createAthlete(profile);const plan=await generateAthletePlan(athlete.athlete_id);saveSession({athleteId:athlete.athlete_id,planId:plan.plan_id});cachePlan(plan.plan);router.push("/");}catch{setStatus("Could not create the plan. Check that the API is running, then try again.");}}return <AppShell title="Create your plan"><form className="onboarding" onSubmit={submit}><label>Name or nickname<input value={name} onChange={e=>setName(e.target.value)}/></label><fieldset><legend>Available rowing days</legend>{weekdays.map(day=><label className="check" key={day}><input type="checkbox" checked={days.includes(day)} onChange={()=>toggle(day,setDays,days)}/>{day}</label>)}</fieldset><fieldset><legend>Lifting days</legend><p>Lifting supports your schedule and recovery; this app does not prescribe lifting workouts.</p>{weekdays.map(day=><label className="check" key={`lift-${day}`}><input type="checkbox" checked={lifts.includes(day)} onChange={()=>toggle(day,setLifts,lifts)}/>{day}</label>)}<label className="check"><input type="checkbox" checked={rowWithLift} onChange={e=>setRowWithLift(e.target.checked)}/>Rowing is possible on my lifting days</label></fieldset><button type="submit">Generate my plan</button><p className="status">{status}</p></form></AppShell>}
