"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "../../components/app-shell";
import { createAthlete, generateAthletePlan } from "../../lib/api";
import { saveSession } from "../../lib/session";
import { cachePlan } from "../../lib/plan-cache";

const weekdays=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"];
const iso=(offset:number)=>{const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)};
export default function Onboarding(){
  const router=useRouter(); const [name,setName]=useState(""); const [start,setStart]=useState(iso(0)); const [end,setEnd]=useState(iso(120)); const [raceDate,setRaceDate]=useState(iso(84)); const [rest,setRest]=useState("saturday"); const [days,setDays]=useState<string[]>(["tuesday","wednesday","thursday","sunday"]); const [resting,setResting]=useState(58); const [maxHr,setMaxHr]=useState(177); const [twoKMin,setTwoKMin]=useState(0); const [twoKSec,setTwoKSec]=useState(0); const [peak,setPeak]=useState(0); const [sixty,setSixty]=useState(0); const [status,setStatus]=useState("");
  const toggle=(day:string)=>setDays(current=>current.includes(day)?current.filter(x=>x!==day):[...current,day]);
  async function submit(event:FormEvent){event.preventDefault();setStatus("Creating your plan…");
    const profile={profile_version:"0.3",athlete:{display_name:name||"Rower",age_band:"30-39",experience_level:"intermediate",boat_classes:[],medical_review_required:false,coach_review_requested:false},season:{start_date:start,end_date:end,current_weekly_endurance_minutes:180,target_peak_weekly_endurance_minutes:270},goals:[],tests:{resting_hr:resting||null,max_hr:maxHr||null,erg_2k_seconds:twoKMin*60+twoKSec||null,multi_duration_power_tests:{...(peak?{short_peak:{value_watts:peak,validity:"valid",test_date:start}}:{}),...(sixty?{one_minute:{value_watts:sixty,validity:"valid",test_date:start}}:{})},testing_blocks:[]},weekly_availability:weekdays.map(day=>({weekday:day,available:days.includes(day),fixed_rest:day===rest,max_training_minutes:90,max_sessions:1,heavy_lifting:false,lifting_minutes:0,alternate_ut2_allowed:false,alternate_ut2_modes:[],row_on_lifting_day:true,fixed_coached_row:false,expected_coached_intensity:"unknown",rowing_modes:["on_water","erg"],notes:""})),races:raceDate?[{event_name:"Primary race",start_date:raceDate,end_date:raceDate,race_type:"head_5k",distance_m:5000,priority:"A",boat_class:"single",expected_races:1,travel_days_before:0,travel_days_after:0,benchmark_for_future_plan:true,notes:""}]:[],preferences:{terminology:"UT",erg_primary_display:"both",broken_aerobic_preferred:true,fixed_rest_weekdays:[rest],workbook_detail_level:"detailed",include_sources_sheet:true},locked_weeks:[]};
    try{const athlete=await createAthlete(profile);const plan=await generateAthletePlan(athlete.athlete_id);saveSession({athleteId:athlete.athlete_id,planId:plan.plan_id});cachePlan(plan.plan);router.push("/");}catch{setStatus("Could not create the plan. Check that the API is running, then try again.");}}
  return <AppShell title="Create your plan"><form className="onboarding" onSubmit={submit}><label>Name or nickname<input value={name} onChange={e=>setName(e.target.value)} /></label><label>Plan starts<input type="date" value={start} onChange={e=>setStart(e.target.value)} required /></label><label>Plan ends<input type="date" value={end} onChange={e=>setEnd(e.target.value)} required /></label><label>Primary race date (optional)<input type="date" value={raceDate} onChange={e=>setRaceDate(e.target.value)} /></label><fieldset><legend>Available rowing days</legend>{weekdays.map(day=><label className="check" key={day}><input type="checkbox" checked={days.includes(day)} onChange={()=>toggle(day)} />{day}</label>)}</fieldset><label>Preferred rest day<select value={rest} onChange={e=>setRest(e.target.value)}>{weekdays.map(day=><option key={day}>{day}</option>)}</select></label><h2>Heart rate and current testing</h2><label>Resting HR<input type="number" value={resting} onChange={e=>setResting(+e.target.value)} /></label><label>Maximum HR<input type="number" value={maxHr} onChange={e=>setMaxHr(+e.target.value)} /></label><label>2k minutes<input type="number" min="0" value={twoKMin} onChange={e=>setTwoKMin(+e.target.value)} /></label><label>2k seconds<input type="number" min="0" max="59" value={twoKSec} onChange={e=>setTwoKSec(+e.target.value)} /></label><label>7-stroke peak watts (optional)<input type="number" min="0" value={peak} onChange={e=>setPeak(+e.target.value)} /></label><label>60-second watts (optional)<input type="number" min="0" value={sixty} onChange={e=>setSixty(+e.target.value)} /></label><button type="submit">Generate my plan</button><p className="status">{status}</p></form></AppShell>;
}
