"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "../../components/app-shell";
import { AthleteCandidate, createAthlete, generateAthletePlan, getAccountAthletes } from "../../lib/api";
import { saveSession } from "../../lib/session";
import { cachePlan } from "../../lib/plan-cache";

const weekdays=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"];
const iso=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const parseTime=(value:string)=>{const match=value.trim().match(/^(\d+):(\d{1,2})$/);return match?Number(match[1])*60+Number(match[2]):null};

function CandidateCard({candidate,onSelect}:{candidate:AthleteCandidate;onSelect:()=>void}){return <article className="activity-card"><b>{candidate.display_name}</b><p>{candidate.season_name||"Season not named"}{candidate.season_start?` · ${candidate.season_start}${candidate.season_end?` to ${candidate.season_end}`:""}`:""}</p><p>{candidate.race_count} races · {candidate.recurring_activity_count} recurring activities · {candidate.performance_test_count} performance tests</p><small>Last updated {new Date(candidate.updated_at).toLocaleDateString()}</small><button type="button" onClick={onSelect}>Use this profile</button></article>}

export default function Onboarding(){
  const router=useRouter();
  const [candidates,setCandidates]=useState<AthleteCandidate[]|null>(null),[lookupError,setLookupError]=useState("");
  const [name,setName]=useState(""),[twoK,setTwoK]=useState(""),[restingHr,setRestingHr]=useState(""),[maxHr,setMaxHr]=useState("");
  const [days,setDays]=useState<string[]>(["tuesday","wednesday","thursday","sunday"]),[lifts,setLifts]=useState<string[]>([]),[rowWithLift,setRowWithLift]=useState(true),[status,setStatus]=useState("");
  const selectExisting=(candidate:AthleteCandidate)=>{saveSession({athleteId:candidate.athlete_id,planId:candidate.plan_id??""});router.push("/profile")};
  useEffect(()=>{getAccountAthletes().then(result=>setCandidates(result.athletes)).catch(()=>setLookupError("We couldn’t confirm your account profile. Please sign in again before creating a profile."));},[]);
  useEffect(()=>{if(candidates?.length===1)selectExisting(candidates[0]);},[candidates]);
  const toggle=(day:string,setter:(v:string[])=>void,items:string[])=>setter(items.includes(day)?items.filter(x=>x!==day):[...items,day]);
  async function submit(event:FormEvent){event.preventDefault();const seconds=twoK?parseTime(twoK):null;if(twoK&&!seconds){setStatus("Enter 2k time as minutes:seconds, for example 8:12.");return;}if(candidates===null||candidates.length){setStatus("Your account already has a profile. Continue with that profile instead of creating another.");return;}setStatus("Creating your plan…");const rest="saturday";const profile={profile_version:"0.6",athlete:{display_name:name||"Rower",age_band:"30-39",experience_level:"intermediate",boat_classes:[],medical_review_required:false,coach_review_requested:false},season:{start_date:iso(0),end_date:iso(120),current_weekly_endurance_minutes:180,target_peak_weekly_endurance_minutes:270},goals:[],tests:{resting_hr:restingHr?Number(restingHr):null,max_hr:maxHr?Number(maxHr):null,erg_2k_seconds:seconds,multi_duration_power_tests:{},testing_blocks:[]},weekly_availability:weekdays.map(day=>({weekday:day,available:days.includes(day),fixed_rest:day===rest,max_training_minutes:90,max_sessions:1,heavy_lifting:lifts.includes(day),lifting_minutes:lifts.includes(day)?60:0,alternate_ut2_allowed:false,alternate_ut2_modes:[],row_on_lifting_day:rowWithLift,fixed_coached_row:false,expected_coached_intensity:"unknown",rowing_modes:["on_water","erg"],notes:""})),races:[],preferences:{terminology:"UT",erg_primary_display:"both",broken_aerobic_preferred:true,fixed_rest_weekdays:[rest],workbook_detail_level:"detailed",include_sources_sheet:true},locked_weeks:[]};try{const athlete=await createAthlete(profile);const plan=await generateAthletePlan(athlete.athlete_id);saveSession({athleteId:athlete.athlete_id,planId:plan.plan_id});cachePlan(plan.plan_id,plan.plan);router.push("/");}catch{setStatus("Could not save your profile because the rowing-plan service could not be reached. Please try again shortly.");}}
  if(lookupError)return <AppShell title="Create your plan"><section className="empty"><p>{lookupError}</p></section></AppShell>;
  if(candidates===null)return <AppShell title="Create your plan"><p>Checking your existing profile…</p></AppShell>;
  if(candidates.length===1)return <AppShell title="Your existing profile"><p>Opening your existing athlete profile…</p></AppShell>;
  if(candidates.length>1)return <AppShell title="Choose your profile"><section className="session-card"><h2>We found more than one rowing profile for your account.</h2><p>Choose the profile you want to continue using. This will not copy, merge, or delete any profile.</p>{candidates.map(candidate=><CandidateCard key={candidate.athlete_id} candidate={candidate} onSelect={()=>selectExisting(candidate)}/>)}</section></AppShell>;
  return <AppShell title="Create your plan"><form className="onboarding" onSubmit={submit}><label>Name or nickname<input value={name} onChange={event=>setName(event.target.value)}/></label><fieldset><legend>Testing (optional)</legend><label>2k time (minutes:seconds)<input value={twoK} onChange={event=>setTwoK(event.target.value)} placeholder="8:12" inputMode="numeric"/></label><label>Resting heart rate<input value={restingHr} onChange={event=>setRestingHr(event.target.value)} inputMode="numeric"/></label><label>Maximum heart rate<input value={maxHr} onChange={event=>setMaxHr(event.target.value)} inputMode="numeric"/></label></fieldset><fieldset><legend>Available rowing days</legend>{weekdays.map(day=><label className="check" key={day}><input type="checkbox" checked={days.includes(day)} onChange={()=>toggle(day,setDays,days)}/>{day}</label>)}</fieldset><fieldset><legend>Lifting days</legend><p>Lifting supports your schedule and recovery; this app does not prescribe lifting workouts.</p>{weekdays.map(day=><label className="check" key={`lift-${day}`}><input type="checkbox" checked={lifts.includes(day)} onChange={()=>toggle(day,setLifts,lifts)}/>{day}</label>)}<label className="check"><input type="checkbox" checked={rowWithLift} onChange={event=>setRowWithLift(event.target.checked)}/>Rowing is possible on my lifting days</label></fieldset><button type="submit">Generate my plan</button><p className="status">{status}</p></form></AppShell>;
}
