"use client";

import Link from "next/link";
import { Suspense, useEffect, useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { AppShell } from "../../components/app-shell";
import { getCurrentAthlete, getLatestAthletePlan, getPlan, getWeek, PlanSession } from "../../lib/api";
import { getSavedSession, saveSession } from "../../lib/session";
import { dailySummary, roleLabel, sessionCategory, workoutStructure } from "../../lib/daily-summary";

type Day={date:string;day:string;state:"designated_rest"|"unavailable"|"no_additional_session";sessions:PlanSession[]};
const monday=(value:string)=>{const d=new Date(`${value}T12:00:00`);d.setDate(d.getDate()-((d.getDay()+6)%7));return d.toISOString().slice(0,10)};
const range=(start:string)=>{const a=new Date(`${start}T12:00:00`),b=new Date(a);b.setDate(b.getDate()+6);return `${a.toLocaleDateString(undefined,{month:"short",day:"numeric"})} – ${b.toLocaleDateString(undefined,{month:"short",day:"numeric"})}`};
function Card({session}:{session:PlanSession}){const coach=session.session_id==="COACHED",strength=session.session_id==="LIFT",race=session.session_id==="RACE";const name=coach?session.title:strength?"Strength":race?"Race":roleLabel(session.session_role);return <Link className={`week-card ${sessionCategory(session)}`} href={`/workout?date=${session.date}&sessionId=${session.session_id}&mode=${session.mode}`}><time>{session.day}<small>{new Date(`${session.date}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</small></time><span className="week-band">{session.band}</span><h2>{name}</h2><p className="week-structure">{coach?"Coach-directed session":strength?"Strength session":workoutStructure(session)}</p><div className="week-metrics"><b>{session.total_cardio_minutes} min</b><span>{session.rating??"Follow coach guidance"}</span><span>{session.hr_range??"Use RPE / breathing"}</span></div></Link>}
function WeekContent(){const [days,setDays]=useState<Day[]>([]),[weeks,setWeeks]=useState<string[]>([]),[planId,setPlanId]=useState(""),[stale,setStale]=useState(false),[loading,setLoading]=useState(true);const params=useSearchParams(),router=useRouter(),path=usePathname(),requested=params.get("week");const selected=useMemo(()=>requested&&weeks.includes(requested)?requested:weeks[0],[requested,weeks]);useEffect(()=>{const load=async()=>{let saved=getSavedSession(), athleteId=saved?.athleteId, activePlanId=saved?.planId; if(!athleteId||!activePlanId){const current=await getCurrentAthlete();athleteId=current.athlete_id;activePlanId=current.plan_id??"";if(activePlanId)saveSession({athleteId,planId:activePlanId});}if(!activePlanId)return;let plan;try{plan=await getPlan(activePlanId);if(plan.athlete_id!==athleteId)throw new Error("Selected athlete mismatch");}catch{plan=await getLatestAthletePlan(athleteId!);activePlanId=plan.plan_id;saveSession({athleteId:athleteId!,planId:activePlanId});}setPlanId(activePlanId);setStale(plan.plan_needs_update);const starts=Array.from(new Set(plan.plan.sessions.map(session=>monday(session.date))));starts.sort();setWeeks(starts);};load().finally(()=>setLoading(false));},[]);useEffect(()=>{if(!planId||!selected||stale)return;setLoading(true);getWeek(planId,selected).then(result=>{setStale(result.plan_needs_update);setDays(result.days);}).finally(()=>setLoading(false));},[planId,selected,stale]);const index=selected?weeks.indexOf(selected):-1;const choose=(week:string)=>router.replace(`${path}?week=${week}`);return <AppShell title="Week"><div className="week-nav"><button className="quiet" disabled={index<=0} onClick={()=>choose(weeks[index-1])}>← Previous week</button><div><b>{selected?range(selected):"Plan week"}</b>{selected&&selected!==weeks[0]&&<button className="quiet" onClick={()=>choose(weeks[0])}>This week</button>}</div><button className="quiet" disabled={index<0||index===weeks.length-1} onClick={()=>choose(weeks[index+1])}>Next week →</button></div><div className="actions"><Link href="/weekly-override">Adjust this week</Link></div>{stale?<section className="notice"><p>Plan needs update.</p><Link href="/profile">Update future plan</Link></section>:loading?<p>Loading plan week…</p>:days.length?<section className="week-cards">{days.map(day=>day.sessions.length?day.sessions.map(session=><Card key={`${session.date}-${session.session_id}-${session.mode}`} session={session}/>):<article className={`week-empty ${day.state}`} key={day.date}><time>{day.day}<small>{new Date(`${day.date}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</small></time><div><b>{dailySummary(undefined,day)}</b></div></article>)}</section>:<p className="empty">No plan week is available.</p>}</AppShell>}
export default function Week(){return <Suspense fallback={<AppShell title="Week"><p>Loading plan week…</p></AppShell>}><WeekContent/></Suspense>}
