"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {AppShell} from "../../components/app-shell";
import {getPlan,getWeek,PlanSession} from "../../lib/api";
import {getSavedSession} from "../../lib/session";
import {roleLabel,sessionCategory,workoutStructure} from "../../lib/daily-summary";
type Day={date:string;day:string;state:"designated_rest"|"unavailable"|"no_additional_session";sessions:PlanSession[]};
const weekNo=(value:string)=>{const date=new Date(`${value}T12:00:00`),target=new Date(date);target.setDate(date.getDate()+4-(date.getDay()||7));return Math.ceil((((target.valueOf()-new Date(target.getFullYear(),0,1).valueOf())/86400000)+1)/7)};
const empty=(state:Day["state"])=>state==="designated_rest"?["Rest","Designated rest day"]:state==="unavailable"?["Unavailable","Unavailable for training"]:["No additional workout","No separate workout required"];
const title=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
function WorkoutCard({session}:{session:PlanSession}){const coach=session.session_id==="COACHED",race=session.session_id==="RACE",strength=session.session_id==="LIFT",role=coach?session.title:race?"Race":strength?"Strength":roleLabel(session.session_role);const detail=coach?(session.title==="Private coaching"?"Coach-directed · technical focus":"Coach-directed row · coach determines content"):race?session.title:strength?"Strength session":workoutStructure(session);return <Link className={`week-card ${sessionCategory(session)}`} href={`/workout?date=${session.date}&sessionId=${session.session_id}&mode=${session.mode}`}><div className="week-card-heading"><time>{session.day}<small>{new Date(`${session.date}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</small></time><span className="week-band">{session.band}</span></div><h2>{role}</h2><p className="week-structure">{detail}</p>{session.recovery&&!coach&&!strength&&<p className="week-recovery">Recovery: {session.recovery}</p>}<div className="week-metrics"><b>{session.total_cardio_minutes} min</b><span>{session.rating??"Follow coach guidance"}</span><span>{session.hr_range??"Use RPE / breathing"}</span>{session.target_watts&&<span>{session.target_watts} W{session.split_guide?` · ${session.split_guide}`:""}</span>}</div>{coach&&<p className="week-coach">Coach instructions take priority.</p>}</Link>}
export default function Week(){const [days,setDays]=useState<Day[]>([]),[stale,setStale]=useState(false),[intent,setIntent]=useState<any>(null);useEffect(()=>{const saved=getSavedSession();if(!saved)return;getPlan(saved.planId).then(plan=>{setStale(plan.plan_needs_update);if(plan.plan_needs_update)return;const first=plan.plan.sessions[0];if(!first)return;const week=weekNo(first.date),start=new Date(`${first.date}T12:00:00`);start.setDate(start.getDate()-((start.getDay()+6)%7));setIntent((plan.plan as any).weekly_training_intents?.find((item:any)=>item.week_start===start.toISOString().slice(0,10))??null);return getWeek(saved.planId,week).then(result=>{setStale(result.plan_needs_update);setDays(result.days);});}).catch(()=>{});},[]);return <AppShell title="Week"><div className="actions"><Link href="/weekly-override">Adjust this week</Link></div>{stale?<section className="notice"><p><b>Plan needs update.</b> Update your plan to view this week.</p><Link href="/profile">Update future plan</Link></section>:days.length?<>{intent&&<section className="week-summary"><span className="band">WEEKLY PLAN</span><h2>{intent.phase_mix?.map((item:any)=>title(item.phase_type)).join(" → ")}</h2><p>Load: {title(intent.load_direction)}</p><div><span>Rowing <b>{intent.target_rowing_sessions}</b></span><span>Strength <b>{intent.target_strength_sessions}</b></span><span>Coaching <b>{(intent.target_private_coaching_sessions??0)+(intent.target_coached_row_sessions??0)}</b></span><span>Rest <b>{intent.target_rest_days}</b></span><span>Target <b>{intent.target_total_rowing_minutes} min</b></span></div>{intent.transition_note&&<p className="note">{intent.transition_note}</p>}</section>}<div className="week-legend" aria-label="Week category legend"><span className="aerobic">Aerobic</span><span className="quality">Quality / threshold</span><span className="high">Race pace</span><span className="strength">Strength</span><span className="coaching">Coaching</span><span className="rest">Rest</span><span className="race">Race</span></div><section className="week-cards">{days.map(day=>day.sessions.length?day.sessions.map(session=><WorkoutCard key={`${session.date}-${session.session_id}-${session.mode}`} session={session}/>):<article className={`week-empty ${day.state}`} key={day.date}><time>{day.day}<small>{new Date(`${day.date}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</small></time><div><b>{empty(day.state)[0]}</b><p>{empty(day.state)[1]}</p></div></article>)}</section></>:<p className="empty">Create a plan to see your week.</p>}</AppShell>}
