"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {AppShell} from "../../components/app-shell";
import {getPlan,getWeek,PlanSession} from "../../lib/api";
import {getSavedSession} from "../../lib/session";
import {dailySummary} from "../../lib/daily-summary";
type Day={date:string;day:string;state:"designated_rest"|"unavailable"|"no_additional_session";sessions:PlanSession[]};
const weekNo=(value:string)=>{const date=new Date(`${value}T12:00:00`),target=new Date(date);target.setDate(date.getDate()+4-(date.getDay()||7));return Math.ceil((((target.valueOf()-new Date(target.getFullYear(),0,1).valueOf())/86400000)+1)/7)};
const emptyLabel=(state:Day["state"])=>state==="designated_rest"?["OFF / REST","Designated rest day"]:state==="unavailable"?["RESTRICTED","Unavailable for training"]:["NO ADDITIONAL SESSION","No separate workout scheduled"];
export default function Week(){const [days,setDays]=useState<Day[]>([]),[stale,setStale]=useState(false),[intent,setIntent]=useState<any>(null);useEffect(()=>{const saved=getSavedSession();if(!saved)return;getPlan(saved.planId).then(plan=>{setStale(plan.plan_needs_update);if(plan.plan_needs_update)return plan;const first=plan.plan.sessions[0];if(first){const week=weekNo(first.date),start=new Date(`${first.date}T12:00:00`);start.setDate(start.getDate()-((start.getDay()+6)%7));setIntent((plan.plan as any).weekly_training_intents?.find((x:any)=>x.week_start===start.toISOString().slice(0,10))??null);return getWeek(saved.planId,week).then(result=>{setStale(result.plan_needs_update);setDays(result.days);return plan;});}return plan;}).catch(()=>{});},[]);return <AppShell title="Week"><div className="actions"><Link href="/weekly-override">Adjust this week</Link></div>{stale?<section className="notice"><p><b>Plan needs update.</b> Your Profile schedule changed, so this older plan is not shown as current.</p><Link href="/profile">Update future plan</Link></section>:days.length?<>{intent&&<section className="session-card"><span className="band">WEEKLY PLAN</span><h2>{intent.phase_mix?.map((x:any)=>x.phase_type.replaceAll("_"," ")).join(" → ")}</h2><p>Load: {intent.load_direction} · Rowing: {intent.target_rowing_sessions} · Strength: {intent.target_strength_sessions} · Rest: {intent.target_rest_days} · Planned rowing: {intent.target_total_rowing_minutes} min</p>{intent.transition_note&&<p className="note">{intent.transition_note}</p>}</section>}{days.map(day=>day.sessions.length?day.sessions.map(session=><Link className="week-row" href={`/workout?date=${session.date}&sessionId=${session.session_id}&mode=${session.mode}`} key={`${session.date}-${session.session_id}-${session.mode}`}><b>{day.day}</b><span>{session.session_role??session.band}</span><span>{dailySummary(session)}</span><span>{session.total_cardio_minutes} min</span></Link>):<article className="week-row rest-row" key={day.date}><b>{day.day}</b><span>{emptyLabel(day.state)[0]}</span><span>{emptyLabel(day.state)[1]}</span><span>—</span></article>)}</>:<p className="empty">Create a plan to see your week.</p>}</AppShell>}
