"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "../../components/app-shell";
import { AthleteCandidate, deleteAccountAthlete, getAccountAthletes } from "../../lib/api";
import { clearCachedPlan } from "../../lib/plan-cache";
import { clearSavedSession, getSavedSession } from "../../lib/session";
import { supabase } from "../../lib/supabase";

const genericEmailMessage = "If that address can receive this email, we sent the next step. Check spam as well.";
const redirectUrl = () => typeof window === "undefined" ? undefined : `${window.location.origin}/account`;
const authMessage = (error: any, signup: boolean) => {
  if (!error) return signup ? "Check your email to confirm your account, then sign in with the password you chose." : "Signed in.";
  const text = String(error.message ?? "").toLowerCase();
  if (text.includes("email not confirmed")) return "Confirm your email, then sign in with the password you chose.";
  if (text.includes("invalid login credentials")) return "That email or password did not match. You can reset your password if needed.";
  if (text.includes("network") || text.includes("fetch")) return "Authentication could not be reached. Check your connection and try again.";
  return signup ? genericEmailMessage : "We couldn’t sign you in right now. Please try again.";
};
function profileStatus(profile: AthleteCandidate, selected: boolean) { if (selected) return "Current profile"; if (profile.deletion_status === "configured") return "Saved setup only"; if (profile.deletion_status === "eligible") return "Empty profile"; return "Training history protected"; }

export default function Account() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [newPassword, setNewPassword] = useState("");
  const [signedIn, setSignedIn] = useState<string | undefined>(); const [message, setMessage] = useState(""); const [recovering, setRecovering] = useState(false);
  const [profiles, setProfiles] = useState<AthleteCandidate[] | null>(null); const [profilesError, setProfilesError] = useState(""); const [deleting, setDeleting] = useState("");
  const selectedAthleteId = getSavedSession()?.athleteId;
  const loadProfiles = async () => { try { const result = await getAccountAthletes(); setProfiles(result.athletes); setProfilesError(""); } catch { setProfilesError("Couldn’t load athlete profiles. Please try again."); } };
  useEffect(() => { supabase?.auth.getUser().then(({ data }) => { setSignedIn(data.user?.email); if (data.user) void loadProfiles(); }); const { data } = supabase?.auth.onAuthStateChange((event, session) => { setSignedIn(session?.user.email); if (session?.user) void loadProfiles(); else setProfiles(null); if (event === "PASSWORD_RECOVERY") setRecovering(true); }) ?? { data: { subscription: { unsubscribe() {} } } }; return () => data.subscription.unsubscribe(); }, []);
  const submit = async (event: FormEvent, signup: boolean) => { event.preventDefault(); if (!supabase) { setMessage("Account setup is not configured yet."); return; } const result = signup ? await supabase.auth.signUp({ email, password, options: { emailRedirectTo: redirectUrl() } }) : await supabase.auth.signInWithPassword({ email, password }); setMessage(authMessage(result.error, signup)); };
  const resend = async () => { if (!supabase || !email) { setMessage("Enter your email address first."); return; } await supabase.auth.resend({ type: "signup", email, options: { emailRedirectTo: redirectUrl() } }); setMessage(genericEmailMessage); };
  const reset = async () => { if (!supabase || !email) { setMessage("Enter your email address first."); return; } await supabase.auth.resetPasswordForEmail(email, { redirectTo: redirectUrl() }); setMessage(genericEmailMessage); };
  const saveNewPassword = async (event: FormEvent) => { event.preventDefault(); if (!supabase) return; const result = await supabase.auth.updateUser({ password: newPassword }); setMessage(result.error?.message ?? "Password updated. You can now sign in."); if (!result.error) setRecovering(false); };
  const signOut = async () => { await supabase?.auth.signOut(); clearSavedSession(); clearCachedPlan(); await caches?.keys?.().then(keys => Promise.all(keys.filter(key => key.startsWith("rowing-plan-")).map(key => caches.delete(key)))); setMessage("Signed out and removed this device’s saved plan data."); };
  const removeProfile = async (profile: AthleteCandidate) => { if (profile.athlete_id === selectedAthleteId) { setMessage("Select another athlete profile before deleting this one."); return; } if (!profile.can_delete) { setMessage("This profile has saved training history and cannot be deleted."); return; } const setupOnly = profile.deletion_status === "configured"; const confirmation = setupOnly ? "This profile contains saved setup information such as availability, races, tests, or preferences.\n\nIt has no generated plans or training history.\n\nDeleting it permanently removes this profile and its setup information." : "This permanently removes this empty/test profile. This cannot be undone."; if (!window.confirm(`Delete this athlete profile?\n\n${confirmation}`)) return; setDeleting(profile.athlete_id); try { await deleteAccountAthlete(profile.athlete_id, selectedAthleteId); setProfiles(current => current?.filter(item => item.athlete_id !== profile.athlete_id) ?? null); setMessage("Profile deleted."); } catch { setMessage("Couldn’t delete that profile. It may contain protected training history."); } finally { setDeleting(""); } };
  if (recovering) return <AppShell title="Set a new password"><form className="onboarding" onSubmit={saveNewPassword}><h2>Set a new password</h2><label>New password<input type="password" autoComplete="new-password" value={newPassword} onChange={event => setNewPassword(event.target.value)} minLength={8} required /></label><button>Save new password</button><p className="status">{message}</p></form></AppShell>;
  if (signedIn) return <AppShell title="Account"><section className="empty"><h2>Signed in</h2><p>{signedIn}</p><p>Account identity is separate from your Athlete Profile.</p><Link href="/profile">Open Athlete Profile</Link><button className="quiet" onClick={signOut}>Sign out</button><p className="status">{message}</p></section><section className="session-card"><h2>Athlete profiles</h2><p>Setup-only duplicates can be removed; profiles with generated plans or training history stay protected.</p>{profilesError && <p role="alert" className="error">{profilesError}</p>}{profiles === null && !profilesError ? <p>Loading athlete profiles…</p> : profiles?.map(profile => { const selected = profile.athlete_id === selectedAthleteId; const status = profileStatus(profile, selected); return <article className="activity-card" key={profile.athlete_id}><b>{profile.display_name}</b><p>{profile.season_name || "Season not named"}</p><p>{status}</p><small>Created {profile.created_at ? new Date(profile.created_at).toLocaleDateString() : "—"} · Updated {new Date(profile.updated_at).toLocaleDateString()}</small>{selected ? <p className="status">Current profile — select another profile before deletion.</p> : profile.can_delete ? <button className="danger" type="button" disabled={deleting === profile.athlete_id} onClick={() => void removeProfile(profile)}>{deleting === profile.athlete_id ? "Deleting…" : "Delete profile"}</button> : <p className="status">Cannot delete — this profile has saved training history.</p>}</article>; })}</section></AppShell>;
  return <AppShell title="Account"><form className="onboarding" onSubmit={event => submit(event, false)}><h2>Private account</h2><p>Your plans and optional health tracking are private to your account.</p><label>Email<input type="email" autoComplete="username" value={email} onChange={event => setEmail(event.target.value)} required /></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={event => setPassword(event.target.value)} minLength={8} required /></label><button>Sign in</button><button type="button" className="quiet" onClick={event => submit(event as unknown as FormEvent, true)}>Create account</button><div className="account-help"><button type="button" className="text-button" onClick={resend}>Resend confirmation email</button><button type="button" className="text-button" onClick={reset}>Reset password</button></div><p className="status">{message}</p></form></AppShell>;
}
